### ISSUE TITLE
Error loading custom_components.krisinformation.sensor

### ISSUE THREAD

**Issue by aronsjoberg** [isabellaalstrom/sensor.krisinformation#14]
Hi!

Everything have worked great until recently. I get this error in the log:

```
2019-04-11 22:34:04 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.krisinformation.sensor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/krisinformation/sensor.py", line 39, in <module>
    from homeassistant.components.rest.sensor import RestData
ModuleNotFoundError: No module named 'homeassistant.components.rest'
2019-04-11 22:34:04 ERROR (MainThread) [homeassistant.loader] Unable to find platform krisinformation.
```

Running Hass.io 0.89.2. I haven't changed anything in my setup AFAIK. Any thoughts or should I just reinstall?

**Comment by isabellaalstrom** [comment]
You seem to have downloaded the newest version, that has a fix needed for 0.91 of Hass, and doesn't work for versions below due to changes in the rest-component. As a quick fix you can go to the row mentioned and change to 
homeassistant.components.sensor.rest
(sensor and rest changes places that is).
