### ISSUE TITLE
Issue with rest sensor in HA 2021.3

### ISSUE THREAD

**Issue by tubalainen** [isabellaalstrom/sensor.krisinformation#28]
Not only the "version warning" in the manifest file - there is something more that needs to be addressed (not sure what).

I am running the beta6 version of the upcoming HA release.

```
2021-03-03 10:57:14 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 834, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 499, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 504, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/krisinformation/sensor.py", line 39, in <module>
    from homeassistant.components.rest.sensor import RestData
ImportError: cannot import name 'RestData' from 'homeassistant.components.rest.sensor' (/usr/src/homeassistant/homeassistant/components/rest/sensor.py)

```

**Comment by isabellaalstrom** [comment]
Rest integration now uses httpx. This should contain example how to use the changed integration as a helper. I will try to look as soon as I can. https://github.com/home-assistant/core/blob/cc72cf0c0d0af3a2121193d34a8ad3dc18100193/homeassistant/components/scrape/sensor.py#L8

**Comment by isabellaalstrom** [comment]
Should be fixed now (as I realized it was only a left over import that I didn't even use :D )
https://github.com/isabellaalstrom/sensor.krisinformation/releases/tag/v1.0.3
